//! Generated gateway bootstrap for sdkwork-order.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_order_service_host::OrderServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<OrderServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_order_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_order_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
