use sdkwork_commerce_contract_service::CommerceServiceContract;

pub fn order_service_contract() -> CommerceServiceContract {
    CommerceServiceContract::new(
        "order",
        "commerce.order",
        vec![
            "checkout.sessions.create",
            "checkout.sessions.quotes.create",
            "checkout.sessions.orders.create",
            "afterSales.requests.create",
            "afterSales.returnShipments.create",
            "afterSales.reviews.create",
            "orders.cancellations.create",
            "shipments.packages.create",
            "shipments.packages.update",
        ],
        vec![
            "checkout.sessions.retrieve",
            "orders.list",
            "orders.retrieve",
            "orders.events.list",
            "afterSales.requests.list",
            "afterSales.requests.retrieve",
            "afterSales.management.list",
            "afterSales.management.retrieve",
            "afterSales.returnShipments.list",
            "afterSales.events.list",
            "fulfillments.list",
            "fulfillments.retrieve",
            "shipments.list",
            "shipments.retrieve",
            "shipments.packages.list",
            "shipments.packages.management.list",
            "shipments.trackingEvents.list",
            "commerceReports.orderRevenue.list",
            "audit.commerceEvents.list",
        ],
        vec![
            crate::ports::ORDER_REPOSITORY_PORT,
            crate::ports::IDEMPOTENCY_REPOSITORY_PORT,
        ],
        true,
    )
}
